// Centralized activity action constants
export const ACTIONS = {
  LOGIN: 'LOGIN',
  LEASE_EXPIRING: 'LEASE_EXPIRING',
  RECEIPT_CREATE: 'RECEIPT_CREATE',
  REMINDER_SENT: 'REMINDER_SENT',
  PAYMENT_CREATE: 'PAYMENT_CREATE',
  PAYMENT_UPDATE: 'PAYMENT_UPDATE',
  PAYMENT_DELETE: 'PAYMENT_DELETE',
  ADMIN_ACTION: 'ADMIN_ACTION',

  TENANT_CREATE: 'TENANT_CREATE',
  TENANT_UPDATE: 'TENANT_UPDATE',
  TENANT_DELETE: 'TENANT_DELETE',

  LEASE_CREATE: 'LEASE_CREATE',
  LEASE_UPDATE: 'LEASE_UPDATE',
  LEASE_DELETE: 'LEASE_DELETE',

  RECEIPT_UPDATE: 'RECEIPT_UPDATE',

  PROFILE_UPDATE: 'PROFILE_UPDATE',
  PASSWORD_CHANGE: 'PASSWORD_CHANGE',

  BUILDING_CREATE: 'BUILDING_CREATE',
  FLOOR_CREATE: 'FLOOR_CREATE',
  SUITE_CREATE: 'SUITE_CREATE',

  // Ticket related actions
  TICKET_CREATE: 'TICKET_CREATE',
  TICKET_UPDATE: 'TICKET_UPDATE',
  TICKET_DELETE: 'TICKET_DELETE',

  SCHEDULER_RUN: 'SCHEDULER_RUN'
};

export default ACTIONS;

// Helper to ensure consistent naming and lookup
export const isValidAction = (a) => !!Object.values(ACTIONS).includes(a);
